version: '3.8'
services:
  postgres:
    image: postgres:16-alpine
    container_name: bch_pool_postgres
    env_file: .env  # ← ЗДЕСЬ подключаем .env
    environment:
      POSTGRES_DB: ${DB_NAME}  # Берём из .env
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"  # DB_PORT из .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U pool_admin -d pool_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: